### ISSUE TITLE
Feature: optional action for rltt_run_training_program when the same training program is running

### ISSUE THREAD

**Issue by maggaou** [Timmeey86/RLTrainingTimer#28]
There is no reason to make separate key binds for rltt_run_training_program, togglemenu rltrainingtimer, etc. This is especially important when having a tenkeyless keyboard which doesn't offer many extra keys. 

rltt_run_training_program could have some other action when the same training is active. When training program abc is currently running, rltt_run_training_program abc could provide one of these actions

- default: the training program will restart normally from the beginning
- display the training program menu to choose other training, to end the training or to pause the training
- pause/unpause the current training
- complete current training pack (I'm not sure if this is different action from unpausing/resume)
- skip the current step and launch the next one (training menu should also include this)

**Comment by Timmeey86** [comment]
`rltt_run_training_program` is a call interface so other plugins can trigger the start of a training program, while `togglemenu rltrainingtimer` opens or closes the UI which is supposed to be used by the player.
