### ISSUE TITLE
hide button

### ISSUE THREAD

**Issue by Raixxor** [Timmeey86/RLTrainingTimer#37]
hi, can you please add a "hide" button, that just hides the entire UI in the view were you start/pause/resume.

**Comment by Raixxor** [comment]
my bad, I should have read the other issues first

**Comment by Timmeey86** [comment]
@Raixxor While you wait for the feature, you can bind "togglemenu rltrainingtimer" to any key in the "Bindings" tab of Bakkesmod

**Comment by Raixxor** [comment]
that opens/closes the little menu, but does not hide the UI (big blue bar at bottom) or at least that is what I meant. I just want to have it look like the base game with the routine being paused (I like to pause my super long routine and jump into games but then resume later)
