### ISSUE TITLE
Pressing "ESC" should not close the training timer (Or should it?)

### ISSUE THREAD

**Issue by eiddor** [Timmeey86/RLTrainingTimer#39]
Since the changes were introduced for "Bottom bar style", pressing Escape while in a training routine will close the RL Training Timer window (bottom bar and training routine remains active.) 

Pressing Escape with previous versions would simply pause RL (and training).  Was this change by design?  I'd rather have to manually click "X" to close the RL Training Timer window.

(Forgive me if I'm not remembering the previous behavior properly.)

**Comment by maggaou** [comment]
I'm using 1.1.0.738. I tested and pressing esc closes the timer window regardless if it has focus or not. There are plugin designs that forces the window be open, see for example https://bakkesplugins.com/plugins/view/98. I'm not sure if controlling the window is possible while it has been forced to be open. When opening console (togglemenu console2), the window becomes possible to control. If there's no solution to that problem, then I suggest not implementing sticking window.

**Comment by eiddor** [comment]
Thanks for the confirmation, @maggaou! I'll just bind a key to re-open the menu if I need it.
